name: pitransf
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Remove this line if no CUDA
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - jupyter
  - ipykernel
  - plotly
  - pip
  
  # Install via pip (packages not available in conda)
  - pip:
    # UMAP for dimensionality reduction (used in your PCA plots)
    - umap-learn>=0.5.0
    
    # Additional scientific packages
    - tqdm  # Progress bars
    - h5py  # HDF5 file format support
    - qutip  # Quantum toolkit (optional)
    # Development and utilities
    - black  # Code formatting
    - flake8  # Code linting
    - pytest  # Testing framework
